import { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Laptop Gaming Pro",
    description: "Potente laptop para gaming y diseño profesional",
    price: 5200000,
    originalPrice: 6000000,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&q=80",
    gallery: [],
    category: "Electrónica",
    stock: 15,
    rating: 4.8,
    isOffer: true,
    discountPercent: 13,
    features: [
      { key: "Marca", value: "ProTech" },
      { key: "Procesador", value: "Intel i9" },
      { key: "RAM", value: "32GB DDR5" },
      { key: "Almacenamiento", value: "1TB SSD" },
      { key: "Pantalla", value: "15.6\" 4K" },
      { key: "Garantía", value: "2 años" },
    ],
  },
  {
    id: "2",
    name: "Smartphone XR Max",
    description: "Smartphone de última generación con cámara 200MP",
    price: 3600000,
    image: "https://images.unsplash.com/photo-1511707267537-b85faf00021e?w=500&q=80",
    gallery: [],
    category: "Accesorios de Celular",
    stock: 32,
    rating: 4.7,
    isOffer: false,
    features: [
      { key: "Marca", value: "XR Mobile" },
      { key: "Cámara", value: "200MP Triple" },
      { key: "Batería", value: "5000mAh" },
      { key: "Pantalla", value: "6.7\" AMOLED" },
      { key: "Garantía", value: "1 año" },
    ],
  },
  {
    id: "3",
    name: "Auriculares Wireless Premium",
    description: "Auriculares con cancelación de ruido activa",
    price: 1200000,
    originalPrice: 1600000,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&q=80",
    gallery: [],
    category: "Parlantes",
    stock: 50,
    rating: 4.6,
    isOffer: true,
    discountPercent: 25,
    features: [
      { key: "Marca", value: "SoundPro" },
      { key: "Conectividad", value: "Bluetooth 5.3" },
      { key: "Batería", value: "30 horas" },
      { key: "Cancelación ruido", value: "Activa ANC" },
      { key: "Garantía", value: "1 año" },
    ],
  },
  {
    id: "4",
    name: "Báscula Digital 5kg",
    description: "Báscula digital de cocina con recipiente plástico",
    price: 45000,
    image: "https://images.unsplash.com/photo-1526408529623-e2b69802b2a8?w=500&q=80",
    gallery: [],
    category: "Básculas Digitales",
    stock: 100,
    rating: 4.9,
    features: [
      { key: "Capacidad", value: "5 kg" },
      { key: "Precisión", value: "1 g" },
      { key: "Material", value: "Plástico" },
      { key: "Garantía", value: "6 meses" },
    ],
  },
  {
    id: "5",
    name: "Linterna LED Recargable",
    description: "Linterna LED de alta potencia con batería recargable",
    price: 35000,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&q=80",
    gallery: [],
    category: "Linternas",
    stock: 40,
    rating: 4.5,
    features: [
      { key: "Tipo", value: "LED" },
      { key: "Batería", value: "Recargable USB" },
      { key: "Garantía", value: "6 meses" },
    ],
  },
  {
    id: "6",
    name: "Kit Herramientas 11 piezas",
    description: "Maletín con 11 herramientas básicas para el hogar",
    price: 65000,
    image: "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=500&q=80",
    gallery: [],
    category: "Herramientas",
    stock: 25,
    rating: 4.7,
    features: [
      { key: "Piezas", value: "11" },
      { key: "Incluye", value: "Martillo, alicates, destornilladores" },
      { key: "Garantía", value: "6 meses" },
    ],
  },
];

export const categories = [
  "Todas",
  "Televentas",
  "Soporte de TV",
  "Ofertas",
  "Accesorios de Celular",
  "Parlantes",
  "Accesorios de Videojuego",
  "Juguetería",
  "Motos",
  "Scooters Eléctricos",
  "Selladoras de Bolsa",
  "Herramientas",
  "Linternas",
  "Básculas Digitales",
  "Hogar",
];
