import { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Laptop Gaming Pro",
    description: "Potente laptop para gaming y diseño profesional",
    price: 5200000,
    originalPrice: 6000000,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&q=80",
    gallery: [],
    category: "Electrónica",
    stock: 15,
    rating: 4.8,
    isOffer: true,
    discountPercent: 13,
    features: [
      { key: "Marca", value: "ProTech" },
      { key: "Procesador", value: "Intel i9" },
      { key: "RAM", value: "32GB DDR5" },
      { key: "Almacenamiento", value: "1TB SSD" },
      { key: "Pantalla", value: "15.6\" 4K" },
      { key: "Garantía", value: "2 años" },
    ],
  },
  {
    id: "2",
    name: "Smartphone XR Max",
    description: "Smartphone de última generación con cámara 200MP",
    price: 3600000,
    image: "https://images.unsplash.com/photo-1511707267537-b85faf00021e?w=500&q=80",
    gallery: [],
    category: "Electrónica",
    stock: 32,
    rating: 4.7,
    isOffer: false,
    features: [
      { key: "Marca", value: "XR Mobile" },
      { key: "Cámara", value: "200MP Triple" },
      { key: "Batería", value: "5000mAh" },
      { key: "Pantalla", value: "6.7\" AMOLED" },
      { key: "Garantía", value: "1 año" },
    ],
  },
  {
    id: "3",
    name: "Auriculares Wireless Premium",
    description: "Auriculares con cancelación de ruido activa",
    price: 1200000,
    originalPrice: 1600000,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&q=80",
    gallery: [],
    category: "Audio",
    stock: 50,
    rating: 4.6,
    isOffer: true,
    discountPercent: 25,
    features: [
      { key: "Marca", value: "SoundPro" },
      { key: "Conectividad", value: "Bluetooth 5.3" },
      { key: "Batería", value: "30 horas" },
      { key: "Cancelación ruido", value: "Activa ANC" },
      { key: "Garantía", value: "1 año" },
    ],
  },
  {
    id: "4",
    name: "Tablet Profesional 12.9",
    description: "Tablet con pantalla OLED para creadores",
    price: 3200000,
    image: "https://images.unsplash.com/photo-1526408529623-e2b69802b2a8?w=500&q=80",
    gallery: [],
    category: "Electrónica",
    stock: 20,
    rating: 4.9,
    features: [
      { key: "Marca", value: "TabPro" },
      { key: "Pantalla", value: "12.9\" OLED" },
      { key: "Procesador", value: "M2 Chip" },
      { key: "Almacenamiento", value: "256GB" },
      { key: "Garantía", value: "1 año" },
    ],
  },
  {
    id: "5",
    name: "Smartwatch Elite",
    description: "Reloj inteligente con monitor de salud avanzado",
    price: 1600000,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&q=80",
    gallery: [],
    category: "Wearables",
    stock: 40,
    rating: 4.5,
    features: [
      { key: "Marca", value: "WatchElite" },
      { key: "Pantalla", value: "AMOLED 1.4\"" },
      { key: "Batería", value: "7 días" },
      { key: "Resistencia", value: "5ATM agua" },
      { key: "Garantía", value: "1 año" },
    ],
  },
  {
    id: "6",
    name: "Cámara DSLR 4K",
    description: "Cámara profesional con lentes intercambiables",
    price: 6400000,
    image: "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=500&q=80",
    gallery: [],
    category: "Fotografía",
    stock: 8,
    rating: 4.9,
    features: [
      { key: "Marca", value: "ProShot" },
      { key: "Resolución", value: "45MP" },
      { key: "Video", value: "4K 120fps" },
      { key: "Montura", value: "Universal" },
      { key: "Garantía", value: "2 años" },
    ],
  },
];

export const categories = ["Todas", "Electrónica", "Audio", "Wearables", "Fotografía"];
